mong/mongts

- next.config.js
Dette gjør at next.js genererer filene som `news/article1/index.html` istedet for `news/article1.html` da skal routing fungere
> Fix s3 filename routing

- .github/dependabot.yml
- package.json
- yarn.lock
- Activate dependabot updates (#40)
- Bump typescript from 4.2.4 to 4.3.5 (#43)
- Bump @types/react from 17.0.6 to 17.0.16 (#45)
- Bump next from 10.2.0 to 11.0.1 (#42)
- Bump prettier from 2.3.1 to 2.3.2 (#41)
> Updates from develop branch

- apps/skde/src/components/MainBanner/MainBanner.tsx
- apps/skde/test/cypress/integration/visitPages.cy.tsx
Part of image got hidden behind another element when using next v13
> Helseatlas: use legacy version of Image on frontpage

- apps/skde/src/charts/barcharts/index.tsx
Fjernet hele (rotateX(90deg)) i transform: ... Dette får feilmeldingen til å forsvinne, og figuren (stolpediagrammet) har fremdeles Opptaksområde riktig vei
Closes #406
> Fjerne feilmelding i logg

- apps/skde/.babelrc
- apps/skde/package.json
- yarn.lock
Nextjs is now using SWC.
This commit closes #618
> Remove babel

- apps/skde/src/components/TableOfContents/ListItem.tsx
First entry in a table of contents has index 0.
Thus should check for where i is a number or defined.
closes #615
> fix(toc): check for if type is number given that first entry has index 0

- apps/api/src/knexfile.ts
Will make it possible to use the app together with imongr. imongr docker-compose will expose port 3331-3333 to db
> api: use user defined port for db if needed

- apps/skde/_posts/helseatlas/statisk/nyfodt_bo.md
- apps/skde/src/components/Atlas/v2/index.tsx
- apps/skde/src/components/Ingress/Ingress.module.css
- apps/skde/src/components/Ingress/index.tsx
- apps/skde/src/components/Static/index.tsx
- apps/skde/src/styles/globals.css
Kan brukes på alle sidene og man får flyttet css ut av global.css. Kjører gjennom markdown.
Closes #637
> Ingress i egen komponent

- package.json
Testing av qmongjs ble ikke kjørt av gh actions, og vi fikk dermed ikke codecov
> Skip turbo cache when testing

- packages/qmongjs/src/helpers/functions/__test__/defineLevel.test.tsx
- packages/qmongjs/src/helpers/functions/defineLevel.ts
- packages/types/src/index.ts
App vil da fungere med gammelt API. Vi kan fjerne dette senere, når vi vet at app bruker siste versjon av api.
> Bruk 'level' i indikatordata, hvis den eksisterer

- packages/qmongjs/src/helpers/functions/__test__/defineLevel.test.tsx
- packages/qmongjs/src/helpers/functions/defineLevel.ts
- packages/types/src/index.ts
This reverts commit 5e907031b40f7bcff5047d803354c22f584c5717.
> Revert "Bruk 'level' i indikatordata, hvis den eksisterer (#748)"

- packages/qmongjs/src/components/Charts/LineChart/__tests__/index.tsx
- packages/qmongjs/src/components/IndicatorTable/chartrow/chartrow.tsx
- packages/qmongjs/src/helpers/functions/__test__/defineLevel.test.tsx
- packages/qmongjs/src/test/test_data/national_data.ts
- packages/types/src/index.ts
Ble tidligere brukt `delivery_time`, som opplaster ikke kunne definere selv. Bruker nå `delivery_latest_update`, som opplaster definerer når hen leverer data.
Closes #824
> Bruk riktig dato-variabel i teksten sist oppdatert

- apps/skde/src/components/CMS/config.ts
Var uklart hva denne gjorde, og den het det samme som lagre-knappen.
> CMS: bedre tekst på publisert-knappen.

- .github/workflows/node.js.yml
- README.md
- apps/api/typedoc.json
- apps/skde/typedoc.json
- package.json
- packages/qmongjs/typedoc.json
- packages/types/typedoc.json
- typedoc.json
- yarn.lock
Ble for mye styr med type-definisjon-konflikter. Ikke mulig å bygge `yarn.lock` fra scratch hvis ny versjon av `@types/react` var ute. Da feilet byggingen av dokumentasjon med en type-error
> Fjernet typedoc

- apps/skde/next.config.js
- apps/skde/package.json
- yarn.lock
Fra [Nextjs 13.1](https://nextjs.org/blog/next-13-1#built-in-module-transpilation-stable) er den inkludert i pakken.
```
next-transpile-modules@npm:10.0.0 is deprecated: All features of next-transpile-modules are now natively built-in Next.js 13.1. Please use Next's transpilePackages option :)
```
> Droppe next-tanspile-modules

- apps/skde/src/components/Atlas/FrontPage/index.tsx
- apps/skde/src/components/Buttons/AtlasLink.tsx
- apps/skde/src/components/Buttons/__tests__/atlaslink.test.tsx
I dag settes siste atlas til nylig publisert, uavhengig av hvor lenge siden det ble publisert:
Endret slik at det, etter 60 dager, ser slik ut:
Kan vurdere om wide også skal droppes?
> Definer om atlas er nylig publisert basert på dato

- apps/skde/src/components/Markdown/__tests__/__snapshots__/markdown.test.tsx.snap
- apps/skde/src/components/Markdown/__tests__/markdown.test.tsx
- apps/skde/src/components/Markdown/index.tsx
De fleste figurene i ortopedi og psyk manglet `alt`. Figur var satt inn med `![](en/eller/annen/kilde.png "En eller annen figurtekst")`, det vil si med tom `[]`.
Vil nå bruke `title`-tekst hvis `alt`-tekst mangler.
Closes #1084
> Markdown: Bruk `title` som `alt` hvis `alt` mangler

- apps/skde/next.config.js
- apps/skde/package.json
- turbo.json
next export is deprecated and replaced with 'output': 'export' (v13.3.0)
> Erstatt next export med output: export i config

- packages/qmongjs/src/components/TargetLevels/__test__/__snapshots__/button.test.tsx.snap
- packages/qmongjs/src/components/TargetLevels/__test__/button.test.tsx
- packages/qmongjs/src/components/TargetLevels/button.tsx
- packages/qmongjs/src/components/TargetLevels/index.module.css
I produksjon kan man ikke lenger se at man har valgt å kun vise gitt måloppnåelse. Det ser det slik ut:
Med denne PR vil det se slik ut:
> reintroduser markering når man har valgt å vise kun en måloppnåelse

- apps/skde/src/components/TableOfContents/ListItem.module.css
- apps/skde/src/helpers/hooks/useintersectionobserver.ts
Fet skrift når seksjon er synlig.
Satt threshold på synlighet, slik at den ikke blir fet hvis kun små deler av seksjon er synlig
> ToC-endringer

- packages/qmongjs/src/components/Charts/LineChart/index.tsx
Ble endret til 0 til yMax i PR #1001. Etter det var det ikke lenger mulig å zoome ut til 100 %. Linjediagram vil nå starte med helt ut-zoomet, fra 0 til 100 %
> Start med zoom 0 til 100 i linjediagram.

- apps/skde/src/components/TableOfContents/__tests__/__snapshots__/tableofcontents.test.tsx.snap
- apps/skde/src/components/TableOfContents/index.tsx
TocDataToList is now used as a tag/component instead of being called as a function.
Note that there is still another bug that must be fixed, but it is unrelated to the page-crash bug described in this issue. The other bug is that several items in the list are shown as bold (active).
> 1221 helseatlas page crashes when changing atlas via menu

- .github/workflows/cypress.yml
- .github/workflows/node.js.yml
- Kjører kun på Node v20.
- Endrer også til å kjøre Cypress med Chrome i stedet for electron, om et lite håp om raskere kjøring (færre timeouts)
- Kjører ikke Cypress-tester på PR inn til dependency_updates
> Kjøre cypress test i egen github action

- packages/qmongjs/src/helpers/functions/__test__/defineLevel.test.tsx
- packages/qmongjs/src/helpers/functions/defineLevel.ts
Grensene er absolutte, før avrunding.
Det blir fort et avvik mellom det som vises i rapportalen og egenberegnet verdier.
Det vil også være avvik i fargen på indikator og det som vises i figurene.
Endres derfor etter diskusjon med Eva og @kevinthon
> Ikke rund av verdi før målnivå-beregning

- packages/qmongjs/src/__test__/app_config.test.ts
- packages/qmongjs/src/app_config.ts
Forgot earlier to increase minYear when increasing maxYear, so number of pickable years increased. This is only relevant for alle-register page.
> Rapportalen: five years pickable as standard

- packages/qmongjs/src/components/SelectYear/__test__/__snapshots__/index.test.tsx.snap
- packages/qmongjs/src/components/SelectYear/__test__/index.test.tsx
- packages/qmongjs/src/components/SelectYear/index.tsx
Var unødvendig. Folk trenger ikke søkemuligheter på år:
La også inn en test.
> Rapportalen: Skip search option in year-selector

- README.md
- package.json
'husky install' is deprecated. Replace it with 'husky'. Renamed command from 'postinstall' to 'prepare', suggested by 'npx husky init'
> Update husky init.

- apps/strapi/package.json
Kan aktivere det igjen når strapi er med klar for produksjon. Slet med å få bygd mongts lokalt.
Closes #2077
> Deaktiver strapi-bygging

- apps/skde/src/components/ResultBox/index.tsx
Som vi diskuterte i stand-up er det sannsynligvis mer intuitivt at man kan lukke ResultBox hvis den også har en hover-effect når den er åpnet. Dette vil også gjøre at ResultBox ligner mer på hvordan FactBox fungerer.
> Lik hover-effekt når ResultBox er lukket og åpen

- apps/skde/pages/behandlingskvalitet/index.tsx
- apps/skde/src/components/TreatmentQuality/index.ts
De fleste moderne desktop-skjermer er over 1300px, mens landskapsvisning på mobil godt kan være så store som 1280px (for eksempel Samsung S23). For disse blir det for lite igjen av skjermen til tabell hvis meny vises permanent. Setter derfor skillet ved 1300px.
> Kun permanent åpen sidemeny når bredden på siden er over 1300px

- packages/qmongjs/src/components/FilterMenu/TreeViewFilterSection.tsx
- packages/qmongjs/src/components/FilterMenu/TreeViewFilterSectionItem.tsx
Tastatursnarveiene for behandlingsenheter er nå som følgende:
Tab og shift-tab for å navigere opp og ned i treet.
Enter for å ekspandere/kollapse noder i treet.
Space for å velge/avvelge enheten.
Kommentar: Å bruke den innebyggede funksjonaliteten med piltaster hadde en issue med at man ikke scrollet nedover hvis listen ble for lang. Man kunne navigere seg nedover med pilene, men dette ble utenfor skjermen. Det var også et problem med at tab-posisjon for neste node og noden som var valgt med piltaster ikke samsvarte. Endte derfor med løsningen som er beskrevet over.
> 2145 tastatursnarvei for ekspandering av behandlingsenheter i filtermeny

- packages/qmongjs/src/components/FilterMenu/TreeViewFilterSection.tsx
Man kan nå bruke shift-tab for å komme ut av treet for behandlingsenhetene, men man må trykke en ekstra gang for å komme til første checkbox og det samme ut igjen.
> fixing issue shift-tab not moving up to parent accordion component

- apps/skde/src/components/TreatmentQuality/TreatmentQualityFooter.tsx
- apps/skde/src/components/TreatmentQuality/index.ts
Overskriftene til indikatortabellen er nå festet slik at de vises selv om man scroller nedover siden.
(Også en ørliten endring i footeren som gjaldt bredde på to grid-kolonner.)
> sticky indicator table header

- apps/skde/pages/behandlingskvalitet/index.tsx
- packages/qmongjs/src/components/FilterMenu/TreatmentQualityFilterMenu/filterMenuOptions.ts
- packages/qmongjs/src/components/FilterMenu/TreatmentQualityFilterMenu/index.tsx
- packages/qmongjs/src/components/FilterMenu/TreeViewFilterSection.tsx
- packages/qmongjs/src/components/FilterMenu/TreeViewFilterSectionItem.tsx
Har lagt til en trevisning der registernavn vises som barn-noder av fagområde. Man kan velge en eller flere register og fagområder. En ekstra feature er at valget for "Alle" automatisk fjernes når man velger huker av et annet fagområde eller register. Det er en generell feature som gjelder trevisninger som aktiveres når "autouncheckid" er satt
> 2199 lage trevisning for valg av register

- apps/api/src/models/info/names.ts
- packages/qmongjs/src/components/FilterMenu/TreatmentQualityFilterMenu/filterMenuOptions.ts
- packages/qmongjs/src/components/SelectRegister/index.tsx
- packages/types/src/index.ts
Dropper ordene norsk/nasjonalt/register, som gikk igjen hos alle. Ekstra kolonne i db må inn for at det skal fungere
Menyene vil se ut som følger:
Ser slik ut i dag:
> Bruk kortnavn på register i stedet for langt navn

- packages/qmongjs/src/components/FilterMenu/TreatmentQualityFilterMenu/index.tsx
- packages/qmongjs/src/components/FilterMenu/TreeViewFilterSection.tsx
- packages/qmongjs/src/components/FilterMenu/TreeViewSearchBox.tsx
For å kunne søke i trevisningene i filtermenyen, er det lagt til en søkeboks over treet.
Det søkes i visningsnavnet til nodene. Treffene er case-insensitive. 
Treff vises i en nedtrekksmeny.
Når brukeren trykker Enter etter å ha valgt, velges noden. Allerede valgte noder blir ikke endret. 
Valget ekspanderes i treet, slik at brukeren ser posisjonen i treet til det som ble valgt. 
Fremtidige forbedringer som ikke er med i denne pull-requesten:
* Noder med ulike id-er, men samme _visningsnavn_ blir valgt samtidig. Bør kunne skille disse på et vis.
* Søkeboksen nullstilles ikke etter et valg, slik at siste valg fortsatt vises i tekstboksen.
> 2304 search box in tree views

- apps/skde/package.json
- packages/qmongjs/package.json
- yarn.lock
Fikk problemer lokalt
> Module parse failed: Cannot use 'import.meta' outside a module
> Nedgrader nextjs fra 14.2.1 til 14.1.4

- apps/skde/pages/behandlingskvalitet/index.tsx
Man kan nå bruke query-parameteret newtable som vil velge nye tabell og fjerne switchen. F. eks.:
http://localhost:3000/behandlingskvalitet/?newtable=true
> new queryparameter "newtable=true" shows new table and removes switch

- packages/qmongjs/src/components/FilterMenu/TreatmentQualityFilterMenu/index.tsx
Now refreshing tree dat after query to api has finished loading
> Fix treatment units tree not initially expanded for selection in query params

- apps/skde/src/components/TreatmentQuality/index.ts
Styling var satt på `table` istedenfor `MuiTable`
> Bug-fiks i ny tabell

- packages/qmongjs/src/components/IndicatorTable/chartrow/Chart.tsx
- packages/qmongjs/src/components/IndicatorTable/chartrow/__tests__/chart.test.tsx
Var allerede definert, og lå i props. Ble definert forskjellig i de to tilfellene. Må legge på ett par dager slik at 31.12 blir 01.01.
Closes #2469
> Dropp redefinering av lastCompleteYear før linechart

- apps/api/src/helpers/functions/nestUnitNames.ts
- apps/api/src/models/data/unitNames.ts
- packages/types/src/index.ts
Gjelder den nestede strukturen av RHF/HF/sykehus.
Relatert til og som en del av løsningen på #2450 og #2468
> Inkluder sorteringsvariabel på hf/rhf i api

- apps/skde/package.json
- packages/qmongjs/package.json
- yarn.lock
Løser enn så lenge #2460. Kommer en permanent fiks i en senere versjon av React. Se f.eks. https://www.github.com/facebook/react/pull/25927
> nedgrader react til 18.2.0

- apps/skde/pages/behandlingskvalitet/index.tsx
- packages/qmongjs/src/components/FilterMenu/SwitchFilterSection.tsx
- packages/qmongjs/src/components/IndicatorTable/index.tsx
- packages/qmongjs/src/components/IndicatorTable/indicatortablebody/index.tsx
- packages/qmongjs/src/components/IndicatorTable/tableblock/index.tsx
- packages/qmongjs/src/components/RegisterPage/SelectedRegister.tsx
- packages/qmongjs/src/components/RegisterPage/main_component.tsx
context var tidligere enten caregiver, resident eller coverage. Ved context lik coverage ble spørringen kun på caregiver-nivå.
> La inn dataQuality som eget argument i indikatortabell-rekka

- apps/skde/pages/behandlingskvalitet/index.tsx
- packages/qmongjs/src/components/FilterMenu/SwitchFilterSection.tsx
- packages/qmongjs/src/components/FilterMenu/TreatmentQualityFilterMenu/index.tsx
- packages/qmongjs/src/components/IndicatorTable/index.tsx
- packages/qmongjs/src/components/IndicatorTable/indicatortablebody/index.tsx
- packages/qmongjs/src/components/IndicatorTable/tableblock/index.tsx
- packages/qmongjs/src/components/RegisterPage/SelectedRegister.tsx
- packages/qmongjs/src/components/RegisterPage/main_component.tsx
Man kan nå velge å vise datakvalitet for opptaksområde.
> Fiks bryter for datakvalitet i filtermeny

- packages/qmongjs/src/components/IndicatorTable/tableblock/index.tsx
Context ble endret i PR #2620, så context lik coverage ikke lenger finnes. Lenker til register ble derfor feil i tabell hvis man var på datakvalitetsfanen, siden den var avhengig av dette.
> Fiks i lenke i tabell i datakvalitetsfane

- apps/skde/src/components/Header/HeaderMiddle.tsx
- apps/skde/src/components/Header/HeaderTop.tsx
- apps/skde/src/components/Header/index.tsx
- apps/skde/src/components/TreatmentQuality/TreatmentQualityAppBar.tsx
- Flyttet topp- og mellom-header til en egen mappe under `components`
- Ny komponent som heter `Header` som kan brukes på behandlingskvalitet og pasientstrømmer
> Egen Header-komponent

- packages/qmongjs/src/components/FilterMenu/TreeViewFilterSection.tsx
- packages/qmongjs/src/components/FilterMenu/TreeViewFilterSectionItem.tsx
Var problemer med ikke-unike ID for registre som lå under flere fagområder. Nå blir ID da fagområde-register.
Closes #2752
> Ta med foreldre-navn på ID i tresktruktur

- apps/skde/src/components/Atlas/FrontPage/FrontPage.module.css
- apps/skde/src/components/Atlas/FrontPage/index.tsx
- apps/skde/src/components/Buttons/AtlasLink.module.css
- apps/skde/src/components/Buttons/AtlasLink.tsx
- apps/skde/src/components/Buttons/__tests__/__snapshots__/atlaslink.test.tsx.snap
- apps/skde/src/components/MainBanner/MainBanner.module.css
Forbedret flex til Helseatlas-forsiden, sånn at det også ser bra ut på mindre skjermer. Jeg endret også stilen på knappene sånn at de ser lik ut knappene på FNSB.
Før: 
Etter:
Den siste linken kan se litt rar ut når den er alene på en linje, fordi den blir litt bredere enn de andre linkene. Men det er et ganske lite problem som sannsynlighvis har en litt for komplisert løsning.
Litt usikker på om vi skal ha denne siden i de nye nettsidene, men det var relativt lett å endre på.
> Forbedret flex til Helseatlas-forsiden

- apps/skde/pages/_document.tsx
Brukte meta-tag fordi man ikke kan returnere statuskoder direkte fra server når man bruker statisk genererte sider (dvs. ingen server). Er i alle fall bedre enn å gjøre en redirect med javascript.
> Redirect from frontpage to skde.no

- apps/skde/src/charts/Abacus/index.tsx
- apps/skde/src/charts/Barchart/__tests__/__snapshots__/barchart.test.tsx.snap
- apps/skde/src/charts/Barchart/index.tsx
- apps/skde/src/charts/Table/__tests__/__snapshots__/table.test.tsx.snap
- apps/skde/src/charts/Table/index.tsx
- apps/skde/src/charts/colors/index.tsx
For stolpediagram og tabell ble label hentet fra data, som var lik for norsk og engelsk atlas. Gjør det nå tilsvarende abacus-plottet.
Closes #2859
> Erstatte Norge med Norway i engelske atlas

- apps/skde/src/charts/Map/index.tsx
Helseatlas for lab hadde noen "jenks"-verdier for kartet som så litt uryddig ut, så jeg gjorde teksten litt mindre hvis jenks-verdien er større enn 10 000, noe som betyr at kartet nå vil støtte jenks verdier opp til 100 000 før tallene begynner å kollidere igjen.
Før:
Etter:
> Gjorde teksten mindre for jenks-verdier i Map-komponentet mindre når verdiene er større enn 10 000

- apps/skde/src/components/TableOfContents/TableOfContents.module.css
I mobilvisning har TableOfContents en hvit bakgrunnsfarge som kræsher med den gråaktige bakgrunnsfargen på resten av helseatlas, så jeg fjernet bagrunnsfargen på liten TOC.
Før:
Etter:
> Fjernet feil bakgrunnsfarge for liten TableOfContents

- apps/skde/src/components/ResultBox/ResultBox.module.css
Fant ut at de fleste nettlesere krever vendor prefixen `-webkit-` for `print-color-adjust`.
> Fikset en CSS property

- packages/qmongjs/src/components/LowLevelIndicatorList/index.tsx
Måloppnåelse med større font og fete typer:
> Formatert tekst i målnivåtabell

- apps/skde/pages/sykehusprofil/index.tsx
"Velg behandlingsenhet"-knappen bruker nå 80 % av skjermbredden hvis den hardkodede lengden er bredere enn 80 % av skjermbredden. 
Før: 
Etter:
> Fikset knapp

- apps/skde/pages/behandlingskvalitet/[registry].tsx
- apps/skde/pages/behandlingskvalitet/index.tsx
- package.json
- packages/qmongjs/src/components/FilterMenu/TreatmentQualityFilterMenu/index.tsx
- packages/qmongjs/src/components/FilterMenu/index.tsx
- packages/qmongjs/src/components/IndicatorTable/index.tsx
På registerspesifikk side:
Når man velger opptaksområde lungekreft for 2024, enten ved å skifte fra behandlingsenheter (default 2024) eller sette year=2024, så blir tabellen skjult fordi valgene kun går til 2023. 
Problemet var at tabellen forsvant for evig og ikke kom tilbake igjen når man valgte andre år.
Dette skal være fikset nå.
En del småendringer ble gjort under feilsøkingen, men selve fiksen er kun endringen i IndicatorTable mellom linje 62-86. IndicatorTableBody må være med selv om den er tom, for ellers vil aldri callback-funksjonen fra denne til IndicatorTable kalles igjen.
> Tabell skjules feilaktig for visse tilfeller

- apps/skde/pages/sykehusprofil/index.tsx
- apps/skde/src/components/HospitalProfile/HospitalProfileLowLevelTable/index.tsx
- Hele siden rendres ikke på nytt når man velger "Vis kvalitetsindikator" eller "Vis datakvalitet" i målnivåtabellen
- Fjernet 36 linjer fra indeksfilen til sykehusprofil
> Målnivnivåtabell i egen komponent i sykehusprofil

- apps/skde/pages/sykehusprofil/index.tsx
- apps/skde/src/components/HospitalProfile/UnitFilterMenu/index.tsx
Flyttet filtermenyen til sykehusprofil ut i en egen komponent. Alle spørringer gjøres i index-filen til siden og sendes til filtermenykomponenten. Komponenten tar også setter-funksjoner for å endre state i hovedkomponenten. 
Når siden bygges skal filtermenyen og knappene for tilknyttede enheter fungerer Knappene fungerer nå stort sett også når man tester med `yarn dev`, men hopper av og til til "Nasjonalt".
> Filtermeny i sykehusprofil i egen komponent

- apps/skde/pages/sykehusprofil/index.tsx
- apps/skde/src/components/HospitalProfile/AffiliatedHospitals/index.tsx
- apps/skde/src/components/HospitalProfile/SubUnits/index.tsx
- apps/skde/src/components/HospitalProfile/UnitFilterMenu/index.tsx
- Oppdater URL i pages-filen istedenfor å sende en setter-funksjon til komponentene under
- Oppdater state istedenfor å laste inn siden på nytt når man velger behandlingsenhet med knappene
- Tilbake-knappen viser enhetsnavn istedenfor "Opp et nivå"
> Sett behandlingsenhet med knapper uten å laste inn siden på nytt

- apps/skde/src/components/HospitalProfile/UnitFilterMenu/index.tsx
- packages/qmongjs/src/components/FilterMenu/CustomAccordionExpandIcon.tsx
- packages/qmongjs/src/components/FilterMenu/TreeViewFilterSectionItem.tsx
- packages/qmongjs/src/components/FilterMenu/index.tsx
- packages/qmongjs/src/themes/SkdeTheme.tsx
En sånn sak som virker enkel, men blir vanskelig fordi 3. part rammeverk/bibliotek ikke er enig. I stedet for å bruke MUI Accordions expandIcon-property, måtte jeg legge til expand-ikonet sammen med teksten i accordion-headeren.
Før/etter
> vertikal posisjon samvarer med tekst, fjerne rotering av ikoner

- packages/qmongjs/src/components/FilterMenu/SelectedFiltersSection.tsx
- packages/qmongjs/src/components/FilterMenu/ToggleButtonFilterSection.tsx
- packages/qmongjs/src/hooks/useElementWidth.ts
- packages/qmongjs/src/themes/SkdeTheme.tsx
Før:
Etter:
Hvis det er plass til begge knappene på samme linje, blir det slik:
Basert på følgende Figma-skisse fra Ramsalt:
> 3111 justeringer av utseendet

- packages/qmongjs/src/components/FilterMenu/ToggleButtonFilterSection.tsx
- packages/qmongjs/src/components/FilterMenu/TreatmentQualityFilterMenu/index.tsx
> En divider og bruk av skip-property for context-valg

- apps/api/src/controllers/data/index.ts
- apps/api/src/controllers/data/registryRank.ts
- apps/api/src/models/data/index.ts
- apps/api/src/models/data/registryRank.ts
- apps/api/src/routes/data.ts
- packages/qmongjs/src/helpers/hooks/apihooks.ts
- packages/qmongjs/src/helpers/hooks/index.ts
- packages/qmongjs/src/index.tsx
- packages/types/src/index.ts
For å teste: http://localhost:4000/data/registryRank?year=2022
Uten `year`-parameteren får man vurderingene for alle år.
> Nytt API-endepunkt for stadiumvurdering

- apps/skde/pages/behandlingskvalitet/[registry].tsx
- apps/skde/pages/stadiumvurdering/[registry].tsx
- Bruk `GetStaticPaths` istedenfor `useRouter`
- Rettet opp i typefeil i behandlingskvalitet
> Lagt til statisk generering av sider på stadiumvurdering/[register]

- apps/skde/src/components/TreatmentQuality/TreatmentQualityToolbar.tsx
Tabellen på siden for behandlingskvalitet er ofte lang og brukeren kan scrolle langt ned. For å gjøre det mer brukervennlig å komme tilbake til toppen, er det lagt inn en "til toppen"-knapp i toolbaren.
Før:
Etter:
> til toppen

- packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx
Bruk MUI sin `Collapse`-komponent for å gjøre rader ekspanderbare istedenfor å sette `visibility` slik at ikke alt skjult innhold må rendres.
> Bruk Collapse i ny tabell

- apps/api/package.json
- package.json
- yarn.lock
Ble lagt inn fordi knip ønsket det, men siste versjon av knip feiler fordi den ligger der.
> Fjern dotenv som avhengighet i api

- .github/workflows/node.js.yml
Code coverage dyttes ikke lenger opp til codecov uten token.
> Bruk codecov-token

- codecov.yml
Tester feilet veldig ofte, selv uten kodeendringer
> Dropp github-sjekk av codecoverage

- apps/skde/src/charts/Barchart/AnnualVarLegend.tsx
- apps/skde/src/charts/Barchart/AnnualVariation.tsx
- apps/skde/src/charts/Barchart/__tests__/__snapshots__/barchart.test.tsx.snap
- apps/skde/src/charts/Barchart/__tests__/barchart.test.tsx
- apps/skde/src/charts/Barchart/index.tsx
Feil skjedde egentlig fordi atlas var satt til `nb` og labels var satt til `nn`. Nå velger den engelsk labels hvis språk-spesifikk labels ikke finnes. Den bygger også hvis labels mangler, og da vises ikke prikkene heller.
> Ikke krasj helseatlas-bygging hvis labels mangler i stolpediagram

- apps/skde/src/components/Footer/__tests__/__snapshots__/footer.test.tsx.snap
- apps/skde/src/components/Footer/index.tsx
- apps/skde/src/components/Static/__tests__/__snapshots__/static.test.tsx.snap
Fixer #3489.
Problemet er at logoen for NSM er gigantisk. Jeg gjorde sånn at logoen krymper hvis skjermen ikke er bred nok:
> Fikset bug i behandlingkvalitet angående bredde

- packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx
Man kan tydeligvis ikke ha en `<p>`-tag inne i en `Typography`-tag.
> Fikset advarsel i ny tabell

- apps/skde/src/components/Atlas/FrontPage/index.tsx
Fikset en typo, og skrev helseatlas med liten h, etter ønske fra ledelsen
> Fikset en typo i den gamle helseatlas-forsiden

- apps/skde/test/cypress/integration/behandlingskvalitet.cy.tsx
Så etter indikator hjerneslag_inn_enhet, men denne finnes ikke lenger ser det ut til. Byttet til hjerneslag_beh_enhet.
> Fiks Cypress-test

- apps/skde/pages/kvalitetsregistre/[register]/[tab].tsx
- apps/skde/pages/kvalitetsregistre/alle/[tab].tsx
- apps/skde/pages/sykehusprofil/index.tsx
- apps/skde/pages/varmekart/index.tsx
- apps/skde/src/components/TreatmentQuality/TreatmentQualityAppBar.tsx
Denne siden brukes ikke lenger. Alt ligger rett på forsiden av skde.no. Closes #3607
> Fjernet 'Tall om helsetjenesten' fra brødsmulesti

- packages/qmongjs/src/components/IndicatorTable/index.tsx
- packages/qmongjs/src/components/IndicatorTable/indicatortablebody/index.tsx
- packages/qmongjs/src/components/IndicatorTable/tableblock/index.tsx
Det finnes en komponent `NoDataAvailible` (sic) som er ment å vises når tabellen er tom. `TableBlock`-komponenten skal gi beskjed til `IndicatorTable`-komponenten to nivå over hvis et register ikke har data via en callback-funksjon. `IndicatorTable` skal telle antall tomme registre, og hvis antallet er lik totalt antall registre vises en `NoDataAvailible`. Dette fungerer ikke slik det er satt opp. 
Et alternativ er å spørre etter data i toppkomponenten og telle rader der. Da kan man også ta hensyn til om data finnes på sykehus eller opptaksområder. Denne løsningen fungerer sammen med #3836.
> Vis noe annet enn tabell når det mangler data i Behandlingskvalitet

- apps/skde/package.json
- packages/qmongjs/package.json
- yarn.lock
Ny versjon 3.0.9 på begge. 
Dette fikser advarsel om at ulike versjoner kan føre til feil:
> Oppdater vitest og vitest-coverage

- yarn.lock
Har kjørt `yarn dedupe express` for å fjerne gamle versjoner som igjen avhenger av gamle versjoner av path-to-regexp. 
Burde løse https://github.com/mong/mongts/security/dependabot/73.
> Fjernet duplikater av express i lock-filen

- packages/qmongjs/src/components/MedfieldTable/__tests__/__snapshots__/medfieldtable.test.tsx.snap
- packages/qmongjs/src/components/MedfieldTable/index.tsx
> Endret kolonnetekst i Sykehusprofil

- apps/skde/pages/helseatlas/admin.jsx
Det funket ikke å logge på i develop, og det virker som det henger sammen med et av scriptene som ble inkludert. I og med at detaljene for github-autentisering ligger i configurasjonen tror jeg ikke dette scriptet er nødvendig.
> Fjernet <script> for identify.netlify.com

- apps/skde/src/helpers/config/CMS-config.ts
Configurasjons-feltet `base_url` var havnet på feil plass. Det kan virke som at /auth er nødvendig i api-et når man hoster CMS-en på nettet, mens at det ikke er nødvendig når man kjører CMS-en lokalt. Hvis man kjører det lokalt går det faktisk an å logge inn med github, og publisere på github-repoet, uten å kjøre en "[oauth proxy](https://decapcms.org/docs/backends-overview/)".
> Flyttet base_url til riktig plass

- apps/skde/src/charts/Barchart/Lollipop.tsx
- apps/skde/src/charts/Barchart/__tests__/__snapshots__/barchart.test.tsx.snap
- apps/skde/src/charts/Barchart/index.tsx
Helseatlas barn2025 hadde behov for å vise data på toppen av et søylediagram som ikke er årsvariasjons-prikker, så vi la til en mulighet for å legge til en "lollipop":
Vi endret også stilen til teksten under grafen, fordi vi syntes den var for in-your-face med font-weight bold og størrelse 14.
> Lollipop for helseatlas

- apps/skde/pages/stadievurdering/[registry].tsx
Hent resultater fra år `defaultYear - 1` og vis dem som Markdown-tekst.
> Markdown i stadievurdering
