components/layout.tsx
pages/index.tsx
styles/Home.module.css

- Added "Om SKDE" as one of the main boxes and removed link in banner
- Removed "Endre tekststørrelse"-info box
- Removed facebook link
- Kvalitetsregistre -> SKDE
- Changed background image

Layout changes

---

.github/workflows/aws_deploy.yml
components/layout.tsx
pages/index.tsx

- deploy main to skde.org and develop to qa (#8)
- url fixes (#14)

develop -> main

---

styles/Home.module.css

Just a few minor changes to the main layout css to narrow down header and footer width and center content.
Closes #35

Limit max-width on header and footer; center content

---

.github/workflows/aws_deploy.yml

Getting ready for Helseatlas v2.0

S3 AWS: do not delete helseatlas folder

---

_posts/aktuelt/eva-stensland-blir-ny-fag-og-forskningssjef-i-skde.md
_posts/innhold/medarbeidere.md
components/layout.tsx
package.json
pages/[slug].tsx
pages/index.tsx
yarn.lock

- Remove news from front page (#122)
- Fix show more button (#110)
- Replace meta data description in head (#108)

Update main with latest develop

---

package.json
pages/aktuelt/[slug].tsx
yarn.lock

Not needed and did not work when updating to next major version

Remove next-mdx-remote

---

.github/workflows/aws_deploy.yml
pages/index.tsx
src/components/layout.tsx

Skip relative path to helseatlas and kvalitetsregistre

Dirty fix of issue #305

---

public/robots.txt

robots.txt file

---

apps/skde/src/components/frontpageLayout.tsx

img 2 Image on front page

---

apps/skde/src/components/Atlas/classic/classic.module.css
apps/skde/src/styles/Atlas.module.css
apps/skde/src/styles/globals.css

Minor css mod

---

packages/qmongjs/src/app_config.ts
packages/qmongjs/src/components/IndicatorTable/indicatortable.tsx
packages/qmongjs/src/components/IndicatorTable/indicatortableheader/indicatortableheader.tsx
packages/qmongjs/src/components/MedicalFields/index.tsx
packages/qmongjs/src/components/RegisterPage/main_component.tsx

Replaced some any with number etc.

Added types on app_config values

---

packages/types/.eslintrc.json
packages/types/src/index.ts

Also included lint config file in package

types: include measure_units in Description

---

apps/skde/src/charts/map/index.tsx

Blue color on HF in map when picked in barchart

---

apps/skde/src/components/Table/index.tsx

Kan markere flere HF.
Closes #559

Marker i tabell HF som er valgt

---

apps/skde/src/components/Atlas/topBanner/index.tsx
apps/skde/src/components/Atlas/topBanner/topbanner.module.css

To please SEO test. Taken from https://github.com/mong/hamongts/pull/651

Remove Link on last breadcrumb element

---

apps/skde/pages/helseatlas/en/static/[slug].tsx
apps/skde/pages/helseatlas/en/v1/[atlas]/index.tsx
apps/skde/pages/helseatlas/en/v2/[atlas]/index.tsx
apps/skde/pages/helseatlas/statisk/[slug].tsx
apps/skde/pages/helseatlas/v1/[atlas]/index.tsx
apps/skde/pages/helseatlas/v2/[atlas]/index.tsx
apps/skde/src/components/Atlas/classic/index.tsx
apps/skde/src/components/Atlas/v2/index.tsx
apps/skde/src/components/Static/index.tsx

Avoid repeating code between english and norwegian pages

Moved helseatlas code from pages/ to src/

---

apps/skde/public/helseatlas/data/endometriose/endom_1921_rate.json
apps/skde/public/helseatlas/data/kronikere/MS_1pasienter_alle.json
apps/skde/public/helseatlas/data/kronikere/MS_2akutt_alle.json
apps/skde/public/helseatlas/data/kronikere/MS_3pasienter_lm.json
apps/skde/public/helseatlas/data/kronikere/Migrene_1pasienter_alle.json
apps/skde/public/helseatlas/data/kronikere/Migrene_2poli_alle.json
apps/skde/public/helseatlas/data/kronikere/Migrene_3pasienter_botox.json
apps/skde/public/helseatlas/data/kronikere/Migrene_4pasienter_sykemld.json
apps/skde/public/helseatlas/data/kronikere/epilepsi_1pasienter_alle.json
apps/skde/public/helseatlas/data/kronikere/epilepsi_2poli_alle.json
apps/skde/public/helseatlas/data/kronikere/epilepsi_3poli_Barn.json
apps/skde/public/helseatlas/data/kronikere/epilepsi_4poli_Eldre.json
apps/skde/public/helseatlas/data/kronikere/epilepsi_5primspes_alle.json
apps/skde/public/helseatlas/data/kronikere/epilepsi_6akutt_alle.json
apps/skde/public/helseatlas/data/kronikere/parkinson_1pasienter_alle.json
apps/skde/public/helseatlas/data/kronikere/parkinson_2poli_alle.json
apps/skde/public/helseatlas/data/kronikere/parkinson_3FLLV_alle.json
apps/skde/public/helseatlas/data/kronikere/parkinson_4NPRKPR_alle.json
apps/skde/public/helseatlas/data/test_atlas/test_data.json
apps/skde/src/charts/abacus/index.tsx
apps/skde/src/charts/barcharts/index.tsx
apps/skde/src/components/ResultBox/resultbox.tsx
apps/skde/src/components/Table/index.tsx

Unngår å hardkode dette til Norge.
Closes #586

Definer hva som er nasjonale tall i dataene

---

apps/skde/pages/helseatlas/en/index.tsx
apps/skde/pages/helseatlas/index.tsx
apps/skde/src/components/Atlas/FrontPage/FrontPage.module.css
apps/skde/src/components/Atlas/FrontPage/index.tsx
apps/skde/src/components/MainBanner/MainBanner.tsx

More sharing of code between english and norwegian page.

Moved Helseatlas front page code into component

---

apps/skde/src/components/Buttons/AtlasLink.tsx
apps/skde/src/components/ImageBox/index.tsx
apps/skde/src/components/MainBanner/MainBanner.module.css
apps/skde/src/components/MainBanner/index.tsx

Use next/image instead of next/legacy/image

---

apps/skde/src/components/Chapters/index.tsx

Add number to Chapter key

---

.github/workflows/codeql-analysis.yml

Only ran it on main and dependency_updates for some reason

Run CodeQL on develop

---

apps/skde/src/components/Atlas/FrontPage/index.tsx
apps/skde/src/helpers/functions/markdownHelpers.ts

Sorter atlas på forsiden etter dato

---

apps/skde/src/components/Atlas/v2/atlas.module.css

Tok css-løsning fra v1 til v2.
Closes #646

Fiks farger på lenker i lister

---

apps/api/src/models/data/selectionyears.ts

Filtrer ut år blant valgbare år som ikke har komplette data

---

apps/skde/src/components/MainBanner/index.tsx

Fix front page image phone scale

---

packages/qmongjs/src/components/IndicatorTable/chartrow/__tests__/__snapshots__/chartrowdescription.tsx.snap
packages/qmongjs/src/components/IndicatorTable/chartrow/chartrowdescription.tsx

Denne hadde sannsynligvis forsvunnet i monorepo-jobben

Fiks av 'Data ble sist oppdatert' tekst

---

packages/qmongjs/src/components/IndicatorTable/chartrow/__tests__/__snapshots__/chartrowdescription.tsx.snap
packages/qmongjs/src/components/IndicatorTable/chartrow/chartrowdescription.tsx

Var 'Data ble sist oppdatert'.
Closes #508

Endret tekst til 'Data ble sist lastet opp'

---

.github/workflows/aws_deploy.yml

I stedet for adressen direkte til cloudfront

Bruk prod-mong-api.skde.org adresse

---

packages/qmongjs/src/components/IndicatorTable/chartrow/chartrow.tsx
packages/qmongjs/src/components/IndicatorTable/indicatorrow/indicatorrow.tsx

Dropp å sende indikator som array hvis det kun er en oppføring

---

apps/skde/test/cypress/integration/kvalitetsregistre.cy.tsx

Feilet hele tiden. Sjekker nå bare at url inneholder year (at år er valgt)

Gjøre test med robust

---

apps/api/src/index.ts

Seems like some people will hit the roof from time to time. If they hit the roof, they only have to wait for 30 seconds

Decrease rate limit window

---

apps/skde/src/components/CMS/config.ts

Henter herfra: https://www.staticcms.org/docs/collection-overview#sortable_fields

CMS: sorter atlas etter publiseringsdato

---

apps/skde/src/components/Atlas/v2/index.tsx

Advarsel på helseatlas hvis det ikke er publisert

---

packages/qmongjs/src/components/Layout/LayoutHead.tsx
packages/qmongjs/src/components/Layout/index.tsx

Ble veldig lite igjen i LayoutHead etter at fontawesome gikk ut

Flyttet kode fra LayoutHead direkte til Layout index

---

packages/qmongjs/src/components/Charts/BarChart/__tests__/__snapshots__/index.tsx.snap
packages/qmongjs/src/components/Charts/BarChart/index.tsx

Litt mindre grått. Flyttet tekst litt opp. Tekst på to linjer. Rød tekst

Endret på 'ikke komplett' over figur

---

apps/skde/_posts/helseatlas/en/atlas/barn.json
apps/skde/_posts/helseatlas/en/atlas/dagkir2.json
apps/skde/_posts/helseatlas/en/atlas/eldre.json
apps/skde/_posts/helseatlas/en/atlas/fodsel.json
apps/skde/_posts/helseatlas/en/atlas/gyn.json
apps/skde/_posts/helseatlas/en/atlas/kols.json
apps/skde/_posts/helseatlas/en/atlas/nyfodt.json
apps/skde/_posts/helseatlas/en/atlas/psyk.json

Lenke til engelske helseatlas-rapporter

---

packages/qmongjs/src/components/IndicatorTable/chartrow/chartrow.tsx

Slå av grønnfarge bak graf hvis indikator ikke har målnivå

---

packages/types/src/index.ts

Enten caregiver eller resident

Tvungen type på context

---

packages/qmongjs/src/components/IndicatorTable/indicatorrow/__test__/__snapshots__/indicatorrow.test.tsx.snap
packages/qmongjs/src/components/IndicatorTable/indicatorrow/__test__/indicatorrow.test.tsx
packages/qmongjs/src/components/IndicatorTable/indicatorrow/index.tsx

Tooltip som forklarer lav N og lav DG

---

packages/qmongjs/src/components/Charts/LineChart/__tests__/__snapshots__/index.tsx.snap
packages/qmongjs/src/components/Charts/LineChart/index.tsx
packages/qmongjs/src/components/IndicatorTable/chartrow/__tests__/__snapshots__/chart.test.tsx.snap

Tick i linjediagram selv om data mangler for gitt år

---

.github/workflows/node.js.yml
apps/skde/pages/helseatlas/en/v2/[atlas]/index.tsx
apps/skde/pages/helseatlas/v2/[atlas]/index.tsx
apps/skde/src/components/Atlas/v2/index.tsx
apps/skde/src/components/Context/index.tsx
apps/skde/src/components/ResultBox/index.tsx

Ikke les inn og pakk geojson-fil under bygging

---

apps/skde/src/charts/Linechart/index.tsx

For å få plass til tick-verdier.
Fra: 
Til:

Linechart: Noe ekstra marg ved y-aksen

---

apps/skde/src/charts/Linechart/ColorLegend.tsx
apps/skde/src/charts/Linechart/index.tsx
apps/skde/src/charts/colors/index.tsx

Ikke bra farger enda. Ikke bra labels heller

Labels og egne farger på linechart

---

packages/qmongjs/src/components/RegisterPage/SelectedRegister.tsx

Bruk registerets siste komplette år som default år

---

apps/skde/src/components/Menu/__tests__/__snapshots__/menu.test.tsx.snap
apps/skde/src/components/Menu/index.tsx

La til endometriose og radiologi 1 på norsk meny og kroniske sykdommer på engelsk
Endometriose lagt under "andre analyser".

Oppdater meny med nye og 'nye' atlas

---

apps/skde/src/components/ResultBox/index.tsx

Fjernet i tillegg ett par `boxData ? ... : undefined;` nedover i koden siden disse ble overflødig.
Closes #1127

Resultatboks: returner ingenting hvis boxData mangler

---

.github/workflows/aws_deploy.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docker.yml
.github/workflows/node.js.yml

For å unngå at det er veldig mange jobber som kjører samtidig. Kun siste som er viktig.
Hentet fra https://stackoverflow.com/a/72408109

Stopp tidligere jobb hvis det kommer ny commit

---

codecov.yml

Patch feilet ofte. Forsøkt slått av. Delt opp i qmongjs og skde.

Endret codecov settings

---

packages/qmongjs/src/components/RegisterPage/header/__test__/__snapshots__/header.test.tsx.snap
packages/qmongjs/src/components/RegisterPage/main_component.tsx
packages/qmongjs/src/components/SelectRegister/index.tsx

Register sorteres alfabetisk under hvert fagområde i indikatorvisningen, og alfabetisk i "Velg register"-menyen.

Registersortering

---

apps/skde/pages/_app.tsx
apps/skde/src/types/_app.d.ts

Added Matomo

---

apps/skde/pages/_document.tsx

Moved meta-tag inside Head. #1464

---

apps/skde/_posts/innhold/personvern.md
apps/skde/test/cypress/integration/app.cy.tsx

Added text concerning privacy for the website, mostly copied from Helse Nord.

---

codecov.yml

Ble for mange falske positive ved oppdatering av pakker

Endre threshold på codecov

---

.github/workflows/aws_deploy.yml
.github/workflows/node.js.yml
apps/api/Dockerfile

Denne er nå den nye LTS-versjonen.
Closes #1551

Oppdater til node 20

---

apps/skde/pages/_app.tsx

updated matomo id.

---

apps/skde/test/cypress/integration/kvalitetsregistre.cy.tsx

øk timeouts på cypress-test

---

apps/api/src/controllers/info/index.ts
apps/api/src/helpers/functions/index.ts
apps/api/src/models/info/index.ts
apps/api/src/models/info/medField.ts
apps/skde/src/components/Buttons/index.ts
apps/skde/src/components/Carousel/index.ts
apps/skde/src/components/Layout/index.ts
apps/skde/src/helpers/functions/index.ts
apps/skde/src/helpers/hooks/index.ts
apps/skde/src/types/index.ts
packages/qmongjs/src/components/IndicatorTable/chartrow/Chart.tsx
packages/qmongjs/src/components/IndicatorTable/chartrow/chartrowbuttons.tsx
packages/qmongjs/src/components/IndicatorTable/chartrow/chartrowdescription.tsx
packages/qmongjs/src/components/IndicatorTable/chartrow/index.ts
packages/qmongjs/src/components/RegisterPage/header/index.ts
packages/qmongjs/src/components/RegisterPage/unitnamelist/index.ts
packages/qmongjs/src/components/RegisterPage/unitnamelist/unitnamelist.tsx
packages/qmongjs/src/helpers/functions/index.ts
packages/qmongjs/src/helpers/hooks/index.ts

Cypress sin komponent-testing klagde på `export * from ...`

Eksplisitt eksportering funksjoner/objekter

---

packages/qmongjs/src/components/Charts/LineChart/__tests__/__snapshots__/index.tsx.snap
packages/qmongjs/src/components/Charts/LineChart/__tests__/index.tsx
packages/qmongjs/src/components/Charts/LineChart/index.tsx

Da vil Nasjonalt få svart farge i linjediagram.
Closes #1029

Sorter labels slik at Nasjonalt alltid er først

---

packages/qmongjs/src/helpers/functions/__test__/filterorderindid.test.tsx
packages/qmongjs/src/helpers/functions/filterorderindid.ts
packages/qmongjs/src/test/test_data/hisreg.ts

Legg indikatorer med name==null sist

---

apps/api/package.json
apps/skde/package.json
apps/skde/src/charts/Abacus/index.tsx
apps/skde/src/charts/Barchart/index.tsx
apps/skde/src/charts/Map/index.tsx
apps/skde/src/charts/Table/index.tsx
apps/skde/src/components/Atlas/v2/index.tsx
apps/skde/src/components/Carousel/Carousel.tsx
apps/skde/src/components/Chapters/index.tsx
packages/qmongjs/package.json
packages/qmongjs/src/components/Charts/BarChart/index.tsx
packages/qmongjs/src/components/Charts/LineChart/legend.tsx
packages/qmongjs/src/components/IndicatorTable/chartrow/chartrow.tsx
packages/qmongjs/src/components/IndicatorTable/chartrow/tr_utils.ts
packages/qmongjs/src/components/IndicatorTable/tableblock/index.tsx
packages/qmongjs/src/components/RegisterPage/MainRegister.tsx
packages/qmongjs/src/components/RegisterPage/SelectedRegister.tsx
packages/qmongjs/src/components/RegisterPage/unitnamelist/unitnamelistbody.tsx
packages/qmongjs/src/components/SelectRegister/index.tsx
packages/qmongjs/src/helpers/functions/filterorderindid.ts
yarn.lock

Annen linting av ternary-operatorene. Blir derfor endring av en del filer.
Se [release notes](https://prettier.io/blog/2023/11/13/3.1.0.html#add-indentation-back-to-nested-ternaries-9559httpsgithubcomprettierprettierpull9559-by-rattrayalexhttpsgithubcomrattrayalex)

Oppdater prettier til v3.1

---

apps/skde/package.json
packages/indexer/package.json
packages/qmongjs/package.json
yarn.lock

Noen nylige innlagte pakker var lagt inn med `^x.y.z`

Eksplisitt versjonering av pakker

---

packages/qmongjs/package.json
yarn.lock

Satse på at vi egentlig ikke trenger denne

Fjern vite-pakke

---

packages/qmongjs/src/components/IndicatorTable/indicatordescription/__test__/__snapshots__/indicatordescription.test.tsx.snap
packages/qmongjs/src/components/IndicatorTable/indicatordescription/index.tsx
packages/qmongjs/src/components/IndicatorTable/indicatordescription/indicatordescription.module.css

Litt annen tekst ('data er komplett til' i stedet for 'data er komplett til og med'
Fra
til

Rød tekst hvis data ikke er komplett.

---

apps/skde/src/components/Menu/__tests__/__snapshots__/menu.test.tsx.snap
apps/skde/src/components/Menu/index.tsx

Oppdatert meny med to nye atlas

---

apps/skde/src/components/ResultBox/index.tsx

Fix expand button aria WCAG errors

---

apps/skde/src/charts/IndicatorLinechart/index.tsx
apps/skde/src/charts/LinechartBase/__tests__/__snapshots__/linechartbase.test.tsx.snap
apps/skde/src/charts/LinechartBase/__tests__/linechartbase.test.tsx
apps/skde/src/charts/LinechartBase/index.tsx

Sett i tillegg på prosentformat når bruker har valgt å vise andel

Format på linechartbase.

---

packages/qmongjs/src/components/FilterMenu/TreatmentQualityFilterMenu.tsx
packages/qmongjs/src/components/FilterMenu/TreeViewFilterSection.tsx
packages/qmongjs/src/components/FilterMenu/TreeViewFilterSectionItem.tsx
packages/qmongjs/src/components/FilterMenu/__test__/TreeViewFilterSection.test.tsx
packages/qmongjs/src/index.tsx

Har lagt til en komponent som setter sammen FilterMenu-komponenter til en meny spesielt for sykehus-/behandlingskvalitet.

filter component tailored for treatment quality page

---

apps/skde/src/charts/Table/__tests__/__snapshots__/table.test.tsx.snap
apps/skde/src/charts/Table/__tests__/table.test.tsx
apps/skde/src/charts/Table/index.tsx

For å gi mulighet for å legge inn linjeskift.
Closes #2061

Kjøre tabell-caption gjennom markdown

---

package.json
yarn.lock

Vil forhåpentligvis løse problemet med lint_staged-kjøring, så folk slutter å commite med --no-verify

prettier som devDep

---

apps/strapi/package.json
yarn.lock

Var en del utdaterte versjoner der, som ga sårbarhetsvarsler.

Oppdater dependencies i strapi-app

---

apps/skde/package.json
packages/qmongjs/package.json
yarn.lock

Fjernet pakkene til @emotions

---

apps/skde/src/components/Layout/FrontPageLayout.tsx

Bytte ansvarlig redaktør fra Barthold til Eva

---

apps/skde/src/charts/Table/__tests__/__snapshots__/table.test.tsx.snap
apps/skde/src/components/Markdown/__tests__/__snapshots__/markdown.test.tsx.snap
apps/skde/src/components/Markdown/index.tsx

Åpne lenker i helseatlas i ny fane

---

apps/skde/pages/behandlingskvalitet/index.tsx
apps/skde/src/components/TreatmentQuality/index.ts
packages/qmongjs/src/components/FilterMenu/TreatmentQualityFilterMenu/index.tsx

Det var en issue rundt at skriften ble veldig liten på mobil når tabellen ble større pga. flere valgte enheter. Nå er det lagt inn horisontal scrollbar når tabellen blir for stor. Har også fjernet en det padding rundt tabell, m.m. Det er også "blurring" langs høyrekanten når tabellen er bredere enn skjermen viser, mest synlig på mobilvisning.

2169 rette skalering og marger behandlingskvalitetsiden

---

apps/skde/pages/behandlingskvalitet/index.tsx
apps/skde/src/components/TreatmentQuality/TreatmentQualityFooter.tsx
apps/skde/src/components/TreatmentQuality/index.ts

Har laget footer med logoer og kontaktinfo. SKDE-logo på appbar vil også bli mindre for små skjermer.

2168 add logos and responsive logo sizes

---

packages/qmongjs/src/components/IndicatorTable/indicatordescription/__test__/__snapshots__/indicatordescription.test.tsx.snap
packages/qmongjs/src/components/IndicatorTable/indicatordescription/index.tsx

Ble smør på flesk, og i enkelte tilfeller misvisende.

Fjernet setningen 'Siste komplette år er ...'

---

packages/qmongjs/src/components/FilterMenu/TreeViewFilterSection.tsx

Fjern andre valg hvis "all" er valgt.

unchecking all others if "all" is selected

---

apps/skde/pages/behandlingskvalitet/index.tsx

La til en switch for å skifte mellom ny og gammel indikatortabell

added switch to toggle between new and old indicator tables

---

packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx

Flyttet kode til egen komponent slik at man kan sette state per komponentkall

Fikset bug med valg av årstall

---

apps/skde/pages/behandlingskvalitet/index.tsx
apps/skde/src/components/Buttons/AtlasLink.tsx
apps/skde/src/components/ImageBox/index.tsx
apps/skde/src/components/Layout/Footer.tsx
apps/skde/src/components/Layout/FrontPageLayout.tsx
apps/skde/src/components/Layout/Header.tsx
apps/skde/src/components/MainBanner/index.tsx
apps/skde/src/components/TreatmentQuality/TreatmentQualityFooter.tsx
apps/skde/src/helpers/functions/imgLoader.tsx
apps/skde/src/helpers/functions/index.ts
packages/qmongjs/src/index.tsx

Lik kode i qmongjs og skde. Closes #2268

Bruk qmongjs sin versjon av imgLoader

---

.github/workflows/dead_links.yml

Da vil klokka være 07:00 her når det er sommertid, og 06:00 når det er vintertid.

dead_links gha Kjør 05.00 UCT

---

apps/strapi/package.json
yarn.lock

Feiler gjennom renovate av en eller annen grunn

Strapi-oppdateringer

---

packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx

Lang indikatorbeskrivelse i ny tabell

---

scripts/atlas/checklinks.py

400 til 402 vil fremdeles returnere feil. Enkelte journaler returnerte 403 når jobb ble kjørt på github.

checklinks: ikke returner feil ved 403

---

.github/workflows/dead_links.yml

Bruk epostliste for utsending av døde-lenker-epost

---

apps/api/package.json
apps/skde/package.json
packages/qmongjs/package.json
yarn.lock

Må sjekke at den fungerer lokalt først

Nedgrader eslint fra 9.0.0 til 8.57.0

---

apps/skde/src/components/Menu/__tests__/__snapshots__/menu.test.tsx.snap
apps/skde/src/components/Menu/index.tsx

radiologi 2 i ToC

---

apps/skde/pages/behandlingskvalitet/index.tsx
packages/qmongjs/src/components/FilterMenu/RadioGroupFilterSection.tsx
packages/qmongjs/src/components/FilterMenu/SelectedFiltersSection.tsx
packages/qmongjs/src/components/FilterMenu/SwitchFilterSection.tsx
packages/qmongjs/src/components/FilterMenu/TreatmentQualityFilterMenu/index.tsx
packages/qmongjs/src/components/FilterMenu/utils.ts
packages/qmongjs/src/index.tsx

Filtervalg og query-parameter for datakvalitet.
Query-parameter dg=true vil filtrere på datakvalitet, mens manglende parameter, tom verdi og andre verdier enn true vil gi indikatorer.

Added query parameter and switch component for data quality

---

apps/skde/pages/behandlingskvalitet/index.tsx
apps/skde/src/components/TreatmentQuality/TreatmentQualityTabs.tsx
apps/skde/src/components/TreatmentQuality/index.ts
packages/qmongjs/src/components/FilterMenu/SwitchFilterSection.tsx
packages/qmongjs/src/components/FilterMenu/TreatmentQualityFilterMenu/index.tsx

Arkfaner for opptaksområde og behandlingsenheter

2372 tabs for resident or caregiver results

---

apps/skde/src/charts/Abacus/__tests__/abacus.test.tsx
apps/skde/src/charts/Barchart/__tests__/barchart.test.tsx
apps/skde/src/charts/IndicatorLinechart/__tests__/indicatorlinechart.test.tsx
apps/skde/src/charts/Map/__tests__/map.test.tsx
apps/skde/src/charts/Table/__tests__/table.test.tsx
apps/skde/src/components/Buttons/__tests__/atlaslink.test.tsx
apps/skde/src/components/Buttons/__tests__/menubutton.test.tsx
apps/skde/src/components/Buttons/__tests__/searchbutton.test.tsx
apps/skde/src/components/Chapters/__tests__/chapters.test.tsx
apps/skde/src/components/ImageBox/__tests__/imagebox.test.tsx
apps/skde/src/components/MainBanner/__tests__/mainbanner.test.tsx
apps/skde/src/components/MedfieldTable/__tests__/medfieldtable.test.tsx
apps/skde/src/components/Static/__tests__/static.test.tsx
apps/skde/src/components/TreatmentQuality/index.ts
packages/qmongjs/src/components/Charts/LinechartBase/__tests__/linechartbase.test.tsx
packages/qmongjs/src/themes/SKDEtheme.tsx

La til Plus Jakarta Sans i theme.

fixed font type, plus jakarta sans

---

packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx

Feil i transformasjon til hierarkisk struktur fungerte ikke med flere år

Fikset bug i ny indikatortabell

---

packages/qmongjs/src/components/Charts/LinechartBase/index.tsx

Bytte punkt midt mellom år + flyttet litt på tooltip

---

packages/types/src/index.ts

Definert types for ny data-struktur

---

apps/skde/pages/varmekart/index.tsx
packages/qmongjs/src/components/Charts/HeatMap/index.tsx
packages/qmongjs/src/components/QualityAtlasFigure/index.tsx

Endret sortering og satt maks størrelse på bokser

---

apps/skde/src/components/Carousel/Carousel.tsx
apps/skde/src/components/Chapters/index.tsx

Jeg syntes måten komponentene FactBox/ResultBox/TextBox ble brukt var litt unødvendig indirekte, så jeg skrev om koden til å bruke disse komponentene direkte (som gjør koden lettere å lese).

Chapter(s) refaktorert

---

apps/api/src/models/data/nestedData.ts
packages/types/src/index.ts

API: Mulighet for å filtrere på id i data

---

apps/skde/pages/helseatlas/en/index.tsx
apps/skde/pages/helseatlas/en/v2/[atlas]/ia.tsx
apps/skde/pages/helseatlas/en/v2/[atlas]/index.tsx
apps/skde/pages/helseatlas/index.tsx
apps/skde/pages/helseatlas/v2/[atlas]/ia.tsx
apps/skde/pages/helseatlas/v2/[atlas]/index.tsx
apps/skde/src/components/Carousel/Carousel.tsx
packages/qmongjs/src/components/Charts/LineChart/legend.tsx
packages/qmongjs/src/components/Charts/LineChart/tooltip.tsx
packages/qmongjs/src/components/FilterMenu/TreeViewFilterSection.tsx
packages/qmongjs/src/components/FilterMenu/TreeViewFilterSectionItem.tsx
packages/qmongjs/src/components/IndicatorTable/ContenForEmptyTable/index.tsx
packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx
packages/qmongjs/src/components/IndicatorTable/chartrow/Chart.tsx
packages/qmongjs/src/components/IndicatorTable/index.tsx
packages/qmongjs/src/components/IndicatorTable/indicatordescription/index.tsx
packages/qmongjs/src/components/IndicatorTable/indicatorrow/index.tsx
packages/qmongjs/src/components/IndicatorTable/indicatortablebody/index.tsx
packages/qmongjs/src/components/IndicatorTable/indicatortableheader/index.tsx
packages/qmongjs/src/components/IndicatorTable/indicatorvalue/index.tsx
packages/qmongjs/src/components/IndicatorTable/maskedindicator/index.tsx
packages/qmongjs/src/components/IndicatorTable/tableblock/index.tsx
packages/qmongjs/src/components/IndicatorTable/tableblock/tableblocktitle.tsx
packages/qmongjs/src/components/MedicalFields/index.tsx
packages/qmongjs/src/components/MedicalFields/medicalfieldentry.tsx
packages/qmongjs/src/components/RegisterPage/MainRegister.tsx
packages/qmongjs/src/components/RegisterPage/SelectedRegister.tsx
packages/qmongjs/src/components/RegisterPage/header/header.tsx
packages/qmongjs/src/components/RegisterPage/header/headertabs.tsx
packages/qmongjs/src/components/RegisterPage/unitnamelist/unitnamelistbody.tsx

Fjerne React.FC

---

packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/IndicatorTableBodyV2Styles.tsx

Bug-fiks i ny tabell

---

packages/qmongjs/src/components/Charts/BarchartBase/__tests__/__snapshots__/barchartbase.test.tsx.snap
packages/qmongjs/src/components/Charts/BarchartBase/index.tsx
packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx

[Screencast from 15. mai 2024 kl. 11.51 +0200.webm](https://github.com/mong/mongts/assets/64078729/504ddb55-aa07-4e86-bc5b-6d33bb600f85)

Knapp for å velge mellom linje- og søylediagram

---

packages/qmongjs/src/components/FilterMenu/TreeViewFilterSection.tsx
packages/qmongjs/src/components/FilterMenu/TreeViewFilterSectionItem.tsx

radiobutton når multiselect === false

---

apps/api/src/helpers/functions/nestedData.ts
packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx
packages/types/src/index.ts

Ble tidligere filtrert ut. Tror denne vil close #2278

Erstatt verdi (var) med null hvis nevner er for lav

---

apps/skde/src/charts/Abacus/index.tsx
apps/skde/src/charts/Barchart/index.tsx
apps/skde/src/charts/Map/index.tsx
apps/skde/src/charts/Table/index.tsx
apps/skde/src/helpers/hooks/index.ts
apps/skde/src/helpers/hooks/useBohfQueryParam.ts

Flyttet logikken for valg av bohf til en egen hook (useBohfQueryParam)

---

apps/skde/next-env.d.ts
apps/skde/tsconfig.json

Ble plutselig plaget med at nextjs la inn dette hver gang jeg kjørte yarn dev eller lignende.
Tror det samme skjedde i #1728

inkluder noe autogenerert konfigurasjon fra nextjs

---

apps/skde/pages/behandlingskvalitet/index.tsx
apps/skde/src/components/TreatmentQuality/TreatmentQualityToolbar.tsx
apps/skde/src/components/TreatmentQuality/index.ts

- Ny bakgrunnsfarge på siden
- Hvit bakgrunn på tabell
- Mellomrom mellom rader i tabell
- Innhold i tabell sentreres vertikalt

Endre bakgrunnsfarge på behandlingskvalitet

---

apps/skde/pages/behandlingskvalitet/index.tsx

Ville ikke ha den bakt inn i selve tabellen. Ser ut til å oppføre seg likt som tidligere.

Flyttet Footer ut av indicatortablewrapper

---

apps/skde/src/components/ArrowLink/index.tsx
apps/skde/src/components/TreatmentQuality/TreatmentQualityHeaderMiddle.tsx

"Mer om kvalitetsregistre"-knapp

---

apps/skde/package.json
packages/qmongjs/package.json
yarn.lock

Advarslene som ble spyttet ut av nextjs er fikset i siste versjon av nextjs

Oppdater React fra 18.2.0 til 18.3.1

---

apps/skde/src/components/ResultBox/index.tsx

Fiks skroll i helseatlas

---

.github/workflows/docker.yml

For å teste om docker image ikke krasjer.

GH action: Bygging og kjøring av docker image

---

apps/skde/pages/behandlingskvalitet/index.tsx
packages/qmongjs/src/components/IndicatorTable/index.tsx
packages/qmongjs/src/components/IndicatorTable/indicatortablebody/index.tsx
packages/qmongjs/src/components/IndicatorTable/tableblock/index.tsx
packages/qmongjs/src/components/IndicatorTable/tableblock/tableblocktitle.tsx

Revert registerknapp i indikatortabell

---

apps/skde/pages/behandlingskvalitet/index.tsx
packages/qmongjs/src/themes/SkdeTheme.tsx

Menyen tok 3 av 12 kolonner tidligere. Går over til 2 av 12 kolonner ved xxxl-skjerm

xxxl-breakpoint ved 2560px. Mindre del til meny.

---

apps/skde/pages/behandlingskvalitet/index.tsx

Mistet mulighet for å scrolle ved overflow

Dropp sticky meny

---

apps/skde/src/components/TreatmentQuality/TreatmentQualityHeaderTop.tsx

Går til https://www.skde.no/resultater

Lagt til tall om helsetjenesten i brødsmulesti

---

apps/skde/src/components/ArrowLink/index.tsx
apps/skde/src/components/Footer/index.tsx
apps/skde/src/components/TreatmentQuality/TreatmentQualityHeaderMiddle.tsx

Manglet `Link`-komponent rundt tekst

Fiks lenker i footer

---

apps/skde/src/components/CMS/config.ts

Må være lite for å gjøre siden lettere

Hint om forsidebilde

---

apps/skde/pages/sykehusprofil/index.tsx

Marginer på footer ble ikke satt fordi siden ikke var satt i `PageWrapper`.

Fiks footer i sykehusprofil

---

apps/api/src/models/data/indicators.ts
apps/skde/test/test_data/data.ts
packages/qmongjs/src/test/test_data/dataBuilder.ts
packages/qmongjs/src/test/test_data/national_data.ts
packages/types/src/index.ts

Fjernet kort og lang indikatorbeskrivelse + `name`

Reduser api data

---

packages/qmongjs/src/components/Charts/LinechartBase/index.tsx
packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx

Valgfri tooltip i linechartbase

---

apps/skde/src/components/Footer/index.tsx
apps/skde/src/components/MedfieldTable/index.tsx
packages/qmongjs/src/components/Charts/LinechartBase/index.tsx
packages/qmongjs/src/components/LowLevelIndicatorList/index.tsx
packages/qmongjs/src/helpers/functions/levelSymbols.tsx

- Manglende key i `MedfieldTable`
- Manglende key i `LowLevelIndicatorList`
- Manglende key i `LinechartBase`
- Desimaltall i bredde på NSM-logo i footer

Fikset advarsler i sykehuprofil

---

packages/qmongjs/src/themes/SkdeTheme.tsx

Det var litt forvirrende at noen fonter hadde to navn (f.eks. "s1" og "subtitle1"), så jeg forenklet koden litt sånn at hver font bare har ett navn.

Forenklet koden til skdeTheme

---

apps/skde/pages/sykehusprofil/index.tsx
packages/qmongjs/src/components/LowLevelIndicatorList/index.tsx

- Fjernet symbol på dekningsgrad
- Fjernet valg om å vise indikatorer som har vært rød de siste fem årene
- Lagt til valg av måloppnåelse

Endret valgmuligheter på lavnivåtabell

---

apps/skde/pages/index.tsx
apps/skde/pages/sykehusprofil/index.tsx
apps/skde/src/charts/Abacus/__tests__/abacus.test.tsx
apps/skde/src/charts/Barchart/__tests__/barchart.test.tsx
apps/skde/src/charts/Map/__tests__/map.test.tsx
apps/skde/src/charts/Table/__tests__/table.test.tsx
apps/skde/src/components/ResultBox/index.tsx
apps/skde/src/components/SubUnits/index.tsx
apps/skde/src/helpers/hooks/useintersectionobserver.ts
package.json
packages/qmongjs/src/components/Charts/BarchartBase/__tests__/barchartbase.test.tsx
packages/qmongjs/src/components/Charts/HeatMap/index.tsx
packages/qmongjs/src/components/Charts/LinechartBase/__tests__/linechartbase.test.tsx
packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx
packages/qmongjs/src/components/LowLevelIndicatorList/index.tsx
packages/qmongjs/src/components/TargetLevels/__test__/button.test.tsx
packages/qmongjs/src/components/TargetLevels/button.tsx
packages/qmongjs/src/helpers/functions/localFormater.ts
packages/qmongjs/src/helpers/hooks/apihooks.ts
yarn.lock

Mange feil av typen:
- error  Expected an assignment or function call and instead saw an expression  @typescript-eslint/no-unused-expressions
- error  A require() style import is forbidden  @typescript-eslint/no-require-imports
- error  'error' is defined but never used  @typescript-eslint/no-unused-vars
Fikset de fleste av den første typen feil. Ignorerte mange av de andre (som regel i tester).

Gjør kode klar for typescript-eslint v8

---

apps/skde/pages/_document.tsx
apps/skde/pages/behandlingskvalitet/index.tsx
packages/qmongjs/package.json
packages/qmongjs/src/components/FilterMenu/RadioGroupFilterSection.tsx
packages/qmongjs/src/components/FilterMenu/SelectedFiltersSection.tsx
packages/qmongjs/src/components/FilterMenu/TreatmentQualityFilterMenu/filterMenuOptions.ts
packages/qmongjs/src/components/FilterMenu/TreatmentQualityFilterMenu/index.tsx
packages/qmongjs/src/components/FilterMenu/utils.ts
yarn.lock

Removed choices for "Alle måloppnåelser" and "Alle fagområder", removed default selections for these, removing deletion icon iff only the defaults for the option are selected.

Removed choices for "Alle måloppnåelser" and "Alle fagområder", etc.

---

apps/skde/src/components/MedfieldTable/__tests__/__snapshots__/medfieldtable.test.tsx.snap
apps/skde/src/components/MedfieldTable/index.tsx
packages/qmongjs/src/components/LowLevelIndicatorList/index.tsx

Lenker til behandlingskvalitet

---

apps/skde/pages/sykehusprofil/index.tsx

Ikke vis underenheter av private helseforetak

---

apps/skde/pages/sykehusprofil/index.tsx

Styling av plot

---

packages/qmongjs/src/components/IndicatorTable/chartrow/Chart.tsx

F. eks. https://apps.skde.no/behandlingskvalitet/?selected_treatment_units=Alta&indicator=reg-gastronet&selected_row=gastronet_svarprosent

Fikset bug i behandlingskvalitet

---

apps/skde/pages/varmekart/index.tsx
apps/skde/src/charts/Linechart/index.tsx
apps/skde/src/components/Chapters/__tests__/__snapshots__/chapters.test.tsx.snap
apps/skde/src/components/Chapters/index.tsx
apps/skde/src/components/PopUp/PopUpContent.tsx
apps/skde/src/components/PopUp/index.tsx
apps/skde/src/components/Static/__tests__/__snapshots__/static.test.tsx.snap
packages/qmongjs/src/components/Charts/LineChart/__tests__/__snapshots__/index.test.tsx.snap
packages/qmongjs/src/components/Charts/LineChart/index.tsx
packages/qmongjs/src/components/Charts/LineChart/tooltip.tsx
packages/qmongjs/src/components/Charts/LinechartBase/index.tsx
packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx
packages/qmongjs/src/components/IndicatorTable/chartrow/__tests__/__snapshots__/chart.test.tsx.snap
packages/qmongjs/src/components/Layout/Header.tsx
packages/qmongjs/src/components/Layout/__test__/__snapshots__/header.test.tsx.snap
packages/qmongjs/src/components/Layout/index.tsx
packages/qmongjs/src/components/LowLevelIndicatorList/index.tsx
packages/qmongjs/src/components/QualityAtlasFigure/index.tsx
packages/qmongjs/src/components/RegisterPage/MainRegister.tsx
packages/qmongjs/src/components/RegisterPage/SelectedRegister.tsx

Inspirert av https://dev.to/_ndeyefatoudiop/101-react-tips-tricks-for-beginners-to-experts-4m11#2-prefer-raw-fragments-endraw-over-dom-nodes-eg-div-span-etc-to-group-elements

Fjernet en del ustylet <div>

---

apps/skde/pages/sykehusprofil/index.tsx

Kart til venstre i infoboks

---

apps/skde/pages/sykehusprofil/index.tsx

Oppdatert headertekst i sykehusprofil

---

apps/skde/pages/sykehusprofil/index.tsx

Full_name i tekst i sykehusprofilbokser

---

apps/skde/pages/sykehusprofil/index.tsx

Endret på tilknyttede behandlingssteder

---

apps/skde/src/components/Footer/index.tsx
apps/skde/src/components/Static/__tests__/__snapshots__/static.test.tsx.snap

Fiks text-advarsel

---

packages/qmongjs/src/components/LowLevelIndicatorList/index.tsx

Tooltip i målnivåtabell

---

packages/qmongjs/src/components/IndicatorTable/chartrow/chartrow.tsx
packages/qmongjs/src/components/IndicatorTable/chartrow/chartrowbuttons.tsx

Laster inn logoen i komponenten over og sender den videre.

Mer robust innlasting av logo i behandlingskvalitet

---

apps/skde/src/components/Header/HeaderTop.tsx

Blir noe tilsvarende slik det er på FNSP.
Closes #2720

Egen brødsmulesti på mobil

---

apps/skde/src/components/TreatmentQuality/TreatmentQualityAppBar.tsx

Få tilbake full brødsmulesti på behandlingskvalitet

---

.github/workflows/aws_deploy.yml
apps/skde/src/components/Header/HeaderMiddle.tsx

Miljøvariablen NEXT_PUBLIC_VERIFY må være definert for at advarsel skal dukke opp. Lenken går til tilsvarende side på apps.skde.no, med de valg to har aktivert.
Closes #524

Advarsel i header hvis bruker er på verify-siden

---

apps/skde/pages/sykehusprofil/index.tsx

Flyttet utvikling over tid

---

apps/skde/src/components/TreatmentQuality/TreatmentQualityAppBar.tsx
apps/skde/src/components/TreatmentQuality/TreatmentQualityToolbar.tsx

Menyknapp på små skjermer ligger i toolbar, så denne ble borte på mobil (closes #3126). Løses også problemet med rader som ble synlig ved scrolling (closes #3103)

Behold Toolbar selv om register mangler data på opptaksomr

---

apps/skde/src/components/HospitalProfile/ExpandableItemBox/index.tsx

Skygge legge på bunne av ekspanderbare bokser når boksen kan ekspanderes:

Skygge på bunnen av boksene

---

apps/skde/pages/sykehusprofil/index.tsx
apps/skde/src/charts/IndicatorLinechart/index.tsx
apps/skde/src/components/HospitalProfile/HospitalProfileLinePlot/index.tsx

- Hele siden rendres ikke lenger på nytt når man veksler mellom "Vis andel" og "Vis antall"
- Index-filen til sykehusprofil er redusert fra 529 til 423 linjer

Utvikling over tid i egen komponent

---

apps/skde/public/helseatlas/data/radiologi2/mr_cervikalkol_tillegg.json
apps/skde/public/helseatlas/data/radiologi2/mr_kol_18_rb1.json
apps/skde/public/helseatlas/data/radiologi2/mr_kol_68_rb1.json
apps/skde/public/helseatlas/data/radiologi2/mr_kol_uspes_rb1.json
apps/skde/public/helseatlas/data/radiologi2/mr_kolumna_rb2.json
apps/skde/public/helseatlas/data/radiologi2/mr_lumbosakral_rb1.json
apps/skde/public/helseatlas/data/radiologi2/mr_lumbosakral_tillegg.json

I created a branch on github and edited English text.  Would like to take these changes into main.

Radio2 atlas eng txt

---

packages/qmongjs/src/components/LowLevelIndicatorList/index.tsx
packages/qmongjs/src/components/MedfieldTable/__tests__/__snapshots__/medfieldtable.test.tsx.snap
packages/qmongjs/src/components/MedfieldTable/index.tsx

Lenkene i fagområdetabell og målnivåtabell går nå til de registerspesifikke sidene. 
Har endret til at lenker fra fagområdetabell åpnes i ny fane.

Lenke til registerspesifikke sider i sykehusprofil

---

apps/skde/src/components/HospitalProfile/HospitalInfoBox/index.tsx
packages/qmongjs/src/components/MedfieldTable/index.tsx

- Advarsel om manglende key
- Advarsel om manglende bildefil når behandlingsenhet ikke er definert

Fikset advarsler i sykehusprofil

---

apps/skde/pages/behandlingskvalitet/[registry].tsx

Glemte i #3085 å endre registerspesifikke sider. Det gjøres nå her. Fant ikke noe issue på denne, men føler det ble nevnt av @jo-inge-arnes  i en eller annen issue.

Bruk breakpoints på registerspes. som på hovedside

---

apps/skde/src/components/Header/HeaderMiddle.tsx

Gjør det mulig å legge inn lenker i header. Closes #3286

subtitle i headermiddle kan inneholde html-kode

---

apps/skde/src/components/HospitalProfile/UnitFilterMenu/index.tsx

Det var forskjell mellom lokal og kjøring på test

en rettelse

---

apps/skde/_posts/helseatlas/en/atlas/lab.json

Janice lager et nytt lab-atlas på engelsk

lab - new english atlas

---

apps/skde/pages/behandlingskvalitet/[registry].tsx
apps/skde/pages/varmekart/index.tsx
apps/skde/src/components/HeatMap/HeatMapFilterMenu.tsx
packages/qmongjs/src/components/FilterMenu/TreatmentQualityFilterMenu/index.tsx

Har lagt til muligheten til å velge bort seksjoner i behandlingskvalitet-filtermenyen. I tillegg kan man sette en egen grense for antall behandlingsenheter som kan velges samtidig.

Skip sections som input til behandlingskvalitets filter komponent

---

apps/skde/pages/behandlingskvalitet/[registry].tsx

Manglet tabell i verify-databasen, så app krasjet

Dropp rank på verify-sidene til register

---

apps/skde/package.json
apps/skde/src/charts/Table/__tests__/__snapshots__/table.test.tsx.snap
apps/skde/src/components/Atlas/TopBanner/__tests__/__snapshots__/topbanner.test.tsx.snap
apps/skde/src/components/Chapters/__tests__/__snapshots__/chapters.test.tsx.snap
apps/skde/src/components/Factbox/__tests__/__snapshots__/factbox.test.tsx.snap
apps/skde/src/components/Static/__tests__/__snapshots__/static.test.tsx.snap
apps/skde/src/components/TableOfContents/__tests__/__snapshots__/tableofcontents.test.tsx.snap
packages/qmongjs/package.json
packages/qmongjs/src/components/Charts/BarChart/__tests__/__snapshots__/index.test.tsx.snap
packages/qmongjs/src/components/Charts/LineChart/__tests__/__snapshots__/index.test.tsx.snap
packages/qmongjs/src/components/IndicatorTable/chartrow/__tests__/__snapshots__/chart.test.tsx.snap
packages/qmongjs/src/components/IndicatorTable/chartrow/__tests__/__snapshots__/chartrowdescription.test.tsx.snap
packages/qmongjs/src/components/MedfieldTable/__tests__/__snapshots__/medfieldtable.test.tsx.snap
yarn.lock

* Update material-ui monorepo
* Oppdater snapshots
---------

Update material-ui monorepo (#3277)

---

packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx

Større eller lik: 
Mindre eller lik:
100 %: 
0 %: 
Ikke oppgitt:

Fikset målnivå i ny tabell

---

packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx
packages/qmongjs/src/components/IndicatorTable/chartrow/chartrow.tsx

Pluss dato for siste opplasting av data

Gamle plot i ny tabell

---

apps/skde/src/components/Menu/__tests__/__snapshots__/menu.test.tsx.snap
apps/skde/src/components/Menu/__tests__/menu.test.tsx
apps/skde/src/components/Menu/index.tsx

Dette burde helt klart skjedd automagisk...

Oppdater helseatlas-meny med nyeste atlas

---

apps/skde/pages/behandlingskvalitet/[registry].tsx
apps/skde/pages/behandlingskvalitet/index.tsx
apps/skde/src/components/TreatmentQuality/index.ts
packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/IndicatorTableBodyV2Styles.tsx
packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx

- Fjernet wrapper og lagt inn styling i den stylede komponenten
- Fast bredde på første kolonne
- Byttet ut "px" med "rem"
- Andeler med fet skrift
- Satt inn `Stack` der ting skal midtjusteres

Små justeringer i ny tabell

---

packages/qmongjs/src/components/IndicatorTable/indicatordescription/index.tsx

Fikset målnivå i gammel tabell

---

apps/api/src/models/data/unitNames.ts

Det skal egentlig være flere forbedringer, men gjør heller denne pullrequest'n liten med kun den ene endringen. Tar de andre tingene i en annen branch/pullrequest. Men bare denne endringen her i seg selv, gjør at spørringene blir mye raskere.

bruk av distinct og uten stjerne ga stor forbedring

---

packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx

Vis grense for lavt målnivå i beskrivelse

---

packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx

Bryt ord i indikatortabellen med bindestrek der det passer

---

packages/qmongjs/src/components/IndicatorTable/tableblock/index.tsx
packages/qmongjs/src/components/IndicatorTable/tableblock/tableblocktitle.tsx

Den er ikke klikkbar med mus, men mulig å trykke på med tab/enter

Fikset url på register-header i tabell

---

apps/skde/app/feed.xml/route.ts
apps/skde/next-env.d.ts
apps/skde/package.json
yarn.lock

Testes ved å gå inn på https://apps.skde.no/feed.xml.

RSS-feed for behandlingskvalitet

---

.github/workflows/aws_deploy.yml
.github/workflows/azure_deploy.yml
.github/workflows/codeql-analysis.yml
.github/workflows/cypress.yml
.github/workflows/dead_links.yml
.github/workflows/deploy_atlasfiles.yml
.github/workflows/docker.yml
.github/workflows/node.js.yml

Ble for mye renovate-PR på github actions

Kun kjør hovedversjoner i github actions

---

apps/api/src/controllers/data/index.ts
apps/api/src/controllers/data/registryScores.ts
apps/api/src/models/data/index.ts
apps/api/src/models/data/registryScores.ts
apps/api/src/routes/data.ts
packages/types/src/index.ts

- Lage en view som returnerer en kolonne med 1 og 0 for de ulike kravene: 
- Legget til et api-endepunkt for å hente ut dataene og bruke det videre til å vise oppnådde krav på kvalitetsregistre.no

Nytt api-endepunkt for måloppnåelse på krav

---

apps/skde/pages/stadiumvurdering/[registry].tsx
apps/skde/pages/stadiumvurderingV2/[registry].tsx
apps/skde/pages/stadiumvurderingV2/index.tsx

For å teste lokalt:
- Gammel løsning: http://localhost:3000/stadiumvurdering/kvarus/
- Ny løsning med vurderingstekst og oppnådde krav: http://localhost:3000/stadiumvurderingV2/kvarus/

Flyttet ny stadiumvurdering til /stadiumvurderingV2

---

apps/skde/src/components/Atlas/FrontPage/index.tsx

Vi har bestemt oss for å bruke begrepet "rapporter" i stedet for "tematiske helseatlas"

Tematiske helseatlas -> Rapporter

---

apps/skde/package.json
apps/skde/src/components/HospitalProfile/UnitFilterMenu/index.tsx
yarn.lock

Fjernet avhengighet av @mui/base

---

.github/workflows/azure_deploy.yml
apps/skde/package.json
apps/skde/pages/index.tsx
yarn.lock

Tror ikke den virker og den sjekkes i hvert fall ikke av noen av oss.
Setter den heller opp igjen hvis ønskelig

Fjerne Sentry

---

apps/api/src/helpers/functions/nestUnitNames.ts
apps/skde/pages/behandlingskvalitet/[registry].tsx
apps/skde/pages/stadiumvurdering/[registry].tsx
apps/skde/pages/stadiumvurderingV2/[registry].tsx
apps/skde/pages/sykehusprofil/index.tsx
apps/skde/src/charts/Abacus/index.tsx
apps/skde/src/charts/Linechart/index.tsx
apps/skde/src/charts/Map/index.tsx
apps/skde/src/charts/Table/index.tsx
apps/skde/src/components/BeadLine/__tests__/beadline.test.tsx
apps/skde/src/components/HospitalProfile/SelectedIndicatorTable/index.tsx
apps/skde/src/components/HospitalProfile/SubUnits/index.tsx
apps/skde/src/components/RegistryLevelTable/index.tsx
packages/qmongjs/src/components/Charts/LineChart/index.tsx
packages/qmongjs/src/components/Charts/LinechartBase/index.tsx
packages/qmongjs/src/components/IndicatorTable/IndicatortablebodyV2/index.tsx
packages/qmongjs/src/components/IndicatorTable/indicatorrow/index.tsx
packages/qmongjs/src/components/IndicatorTable/tableblock/index.tsx
packages/qmongjs/src/components/LowLevelIndicatorList/index.tsx
packages/qmongjs/src/components/QualityAtlasFigure/index.tsx
packages/qmongjs/src/components/RequirementList/index.tsx
packages/qmongjs/src/helpers/functions/filterorderindid.ts
packages/qmongjs/src/helpers/functions/getUnitName.tsx
packages/qmongjs/src/helpers/functions/validateTreatmentUnits.ts

Jeg la merke til at vi ofte bruker Array.filter når det egentlig er bedre å bruke Array.find (fordi vi bare skal finne én ting). Så jeg søkte etter bruk av filter og endret til find når dette var tilfellet. Dette fører til en liten reduksjon i kodekompleksitet.

Bruke av Array.find() istendenfor Array.filter()[0]

---

apps/skde/package.json
apps/skde/src/components/Chapters/Chapters.module.css
apps/skde/src/components/Chapters/__tests__/__snapshots__/chapters.test.tsx.snap
apps/skde/src/components/Chapters/index.tsx
apps/skde/src/components/Factbox/__tests__/__snapshots__/factbox.test.tsx.snap
apps/skde/src/components/Factbox/index.tsx
apps/skde/src/components/ResultBox/index.tsx
apps/skde/src/components/TableOfContents/__tests__/__snapshots__/tableofcontents.test.tsx.snap
package.json
packages/qmongjs/package.json
packages/qmongjs/src/components/IndicatorTable/chartrow/__tests__/__snapshots__/chartrowdescription.test.tsx.snap
packages/qmongjs/src/components/MedfieldTable/__tests__/__snapshots__/medfieldtable.test.tsx.snap
packages/qmongjs/src/components/RequirementList/__tests__/__snapshots__/index.test.tsx.snap
yarn.lock

Helseatlas fontfix

---

renovate.json

Dropp å kjøre de inn i dependency_updates-grena først. Kjører patch inn automatisk. Manuell innkjøring av minor og major

Dytt oppdateringer av pakker inn i develop

---

packages/qmongjs/package.json
packages/qmongjs/src/Globals.d.ts
packages/qmongjs/src/react-app-env.d.ts
packages/qmongjs/tsconfig.json
yarn.lock

Brukes ikke og laster inn mange andre pakker.

Fjernet react-scripts

---

apps/api/package.json
yarn.lock

Express 5 ødela api-et. Alle behandlingsenheter lastes inn.

Rull tilbake express

---

.github/workflows/azure_deploy.yml

Det er komplisert å få login til å virke for user-assigned managed identity. Prøver andre parametre.

nytt oppsett for azure login

---

apps/skde/src/components/Footer/__tests__/__snapshots__/footer.test.tsx.snap
apps/skde/src/components/Footer/index.tsx
apps/skde/src/components/Static/__tests__/__snapshots__/static.test.tsx.snap

Flere lenker i Footeren har blitt utdatert og gir 404.

Oppdaterte lenker i footeren

---

apps/skde/pages/behandlingskvalitet/index.tsx

Fjernet ordet cachetest fra tittel, se issue #3958

Fjernet ordet cachetest fra tittel

---

apps/skde/src/components/Footer/index.tsx

`layout` støttes ikke lenger i `Image`

Oppdatert prop i Image

---

.github/workflows/azure_deploy.yml

Vi skal nå omsider ha fått riktige rettigheter til å slette cache fra github

Sletting av front door cache ved bygging av nye sider

---

apps/skde/next-env.d.ts
apps/skde/src/components/HospitalProfile/SelectedIndicatorTable/index.tsx

Test for manglende data var ikke tilstrekkelig robust.

Fikset krasj i Sykehusprofil

---

apps/skde/pages/behandlingskvalitet/[registry].tsx

Hent `defaultReviewYear` istedenfor `defaultYear`.

Endret år på vist stadium på registerspesifikke sider
